// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Roller3

lv_obj_t * ui_Roller3_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Roller3;
    cui_Roller3 = lv_roller_create(comp_parent);
    lv_roller_set_options(cui_Roller3, "Option 1\nOption 2\nOption 3\nOption 4\nOption 5\nOption 6\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(cui_Roller3, 157);
    lv_obj_set_width(cui_Roller3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(cui_Roller3, 1);
    lv_obj_set_y(cui_Roller3, -1);
    lv_obj_set_align(cui_Roller3, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_ROLLER3_NUM);
    children[UI_COMP_ROLLER3_ROLLER3] = cui_Roller3;
    lv_obj_add_event_cb(cui_Roller3, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Roller3, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Roller3_create_hook(cui_Roller3);
    return cui_Roller3;
}

