// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_ROLLER3_H
#define _UI_COMP_ROLLER3_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Roller3
#define UI_COMP_ROLLER3_ROLLER3 0
#define _UI_COMP_ROLLER3_NUM 1
lv_obj_t * ui_Roller3_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
